spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    ssl:
      trust-store-location: ${TRUSTSTORE_LOCATION}
      trust-store-password: ${TRUSTSTORE_PASSWORD}
      key-store-location: ${KEYSTORE_LOCATION}
      key-store-password: ${KEYSTORE_PASSWORD}
    properties:
      security:
        protocol: "SSL"
      ssl:
        endpoint:
          identification:
            algorithm: ""
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer